### ISSUE TITLE
关于版本兼容性？

### ISSUE THREAD

**Issue by Muska-Ami** [bunnyi116/bukkit-syncmatica#1]
我翻了每一个类文件的导入，似乎没有看到任何使用到NMS的部分，请问这个插件是否兼容1.20.1+呢

**Comment by bunnyi116** [comment]
该项目使用 spigot 开发，基于 fabric-syncmatica 1.20.1 开发，据我所知，在1.20.1之后的版本在Minecraft原版代码中发生了大改动，所以大概率是不兼容1.20.1之后的版本。

由于我的工作原因，这个项目将会被搁置，我很抱歉！

**Comment by bunnyi116** [comment]
至于 NMS 我不明白你指的是什么东西，能否解释一下。

**Comment by bunnyi116** [comment]
我搜索了一下，NMS 是自定义实体是吗？

我想说明一下，该项目主要功能是围绕客户端fabric客户端的syncmatica模组进行开发的，主要功能是投影文件同步与分享，让装有同模组的其他玩家也能看见别人分享的投影位置。本插件不涉及渲染，主要渲染都是由客户端模组进行实现，本插件只是实现服务端与客户端通信的自定义通道协议，换句话说，该插件只是一个实现了syncmatica模组网络通讯协议的插件。

**Comment by bunnyi116** [comment]
我搜索了一下，NMS 是自定义实体是吗？

我想说明一下，该项目主要功能是围绕客户端fabric客户端的syncmatica模组进行开发的，主要功能是投影文件同步与分享，让装有同模组的其他玩家也能看见别人分享的投影位置。本插件不涉及渲染，主要渲染都是由客户端模组进行实现，本插件只是实现服务端与客户端通信的自定义通道协议，换句话说，该插件只是一个实现了syncmatica模组网络通讯协议的插件。

**Comment by bunnyi116** [comment]
如果你想了解投影和共享原理图可以参考以下连接
https://github.com/maruohon/litematica
https://github.com/End-Tech/syncmatica

**Comment by Muska-Ami** [comment]
> 我搜索了一下，NMS 是自定义实体是吗？
> 
> 我想说明一下，该项目主要功能是围绕客户端fabric客户端的syncmatica模组进行开发的，主要功能是投影文件同步与分享，让装有同模组的其他玩家也能看见别人分享的投影位置。本插件不涉及渲染，主要渲染都是由客户端模组进行实现，本插件只是实现服务端与客户端通信的自定义通道协议，换句话说，该插件只是一个实现了syncmatica模组网络通讯协议的插件。

并不是的，NMS指的是 `net.minecraft.server` 包的内容，而平时所说的NMS指的是NMS反射，即直接重写或者使用NMS类中的API进行操作

**Comment by Muska-Ami** [comment]
我看到这个项目中并没有导入相关部分，而是使用了通用的Bukkit API，Bukkit API在1.12.2+后基本一致，所以才会想到是否能跨版本使用

**Comment by bunnyi116** [comment]
> 我看到这个项目中并没有导入相关部分，而是使用了通用的Bukkit API，Bukkit API在1.12.2+后基本一致，所以才会想到是否能跨版本使用

感谢你的解答，该插件并没有使用NMS实现，本插件是基于Minecraft中的自定义通道数据包(Bukkit API已给我们实现了)进行注册收发数据，然后根据共享投影模组中实现的通信协议数据的格式进行交互。

关于兼容性问题，这要看BukkitAPI自定义数据包和syncmatica数据格式是否发生变化，如果内容没有变化，应该是通用的

**Comment by bunnyi116** [comment]
https://wiki.vg/Plugin_channels
https://wiki.vg/Protocol#Clientbound_Plugin_Message_.28configuration.29

**Comment by bunnyi116** [comment]
在1.20.1以后版本中，据我所知Minecraft相关的协议有发生改动，但由于我需要工作，没有时间去研究这个新的协议。

**Comment by bunnyi116** [comment]
https://wiki.vg/Protocol#Clientbound_Plugin_Message_.28play.29

**Comment by Muska-Ami** [comment]
感谢回复。或许有时间我会尝试兼容最新版本并集成到我的服务器核心组件中

**Comment by bunnyi116** [comment]
> 感谢回复。或许有时间我会尝试兼容最新版本并集成到我的服务器核心组件中

我已经将我的 [fabric-syncmatica](https://github.com/bunnyi116/fabric-syncmatica/releases) 分支进行了兼容，原作者版本我已经发起PR了等待处理，可以暂时使用我的分支版本 [releases](https://github.com/bunnyi116/bukkit-syncmatica/releases)

**Comment by bunnyi116** [comment]
已兼容1.20.1+，Issues关闭
